spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socialCommerce?createDatabaseIfNotExist=true
    username: root
    password: Root1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create

  ## MULTIPART (MultipartProperties)
  # Enable multipart uploads
  servlet:
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: C:/react/socialCommerceBE/images
app:
  enabledLocales:
    - en