version: '3.7'

services:
  social-commerce-database:
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: Root1234!
      MYSQL_DATABASE: socialCommerce
      MYSQL_ROOT_HOST: '%'
    networks:
      - backend
  social-commerce-backend:
    build: social-commerce-backend\
    ports:
      - 8080:8080
    depends_on:
      - social-commerce-database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://social-commerce-database:3306/socialCommerce?userSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root1234!
    networks:
      - backend
  social-commerce-frontend:
    build: social-commerce-frontend\
    ports: 
      - 3000:3000
    depends_on:
      - social-commerce-backend
    networks:
      - backend

networks:
  backend: